# Generated by Django 4.1.4 on 2022-12-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
